@echo off
cd "%userprofile%\desktop"
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
echo REKT > REKT.virus
